version: '3.8'

services:
  deca-backend:
    build: .
    container_name: deca_saas_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data